apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
  namespace: vote
spec:
  selector:
    app: db
  ports:
  - name: "db-service" 
    port: 5432
    targetPort: 5432
  type: ClusterIP
