apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  namespace: vote
spec:
  selector:
    app: redis
  ports:
  - name: "redis-service" 
    port: 6379
    targetPort: 6379
  type: ClusterIP
