apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
  namespace: vote
spec:
  selector:
    app: result
  ports:
  - name: "result-service" 
    port: 5001
    targetPort: 80
  type: NodePort
