apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
  namespace: vote
spec:
  selector:
    app: vote
  ports:
  - name: "vote-service" 
    port: 5000
    targetPort: 80
  type: NodePort
